pool:
  name: MyLocalAgentPool

variables:
  BuildConfiguration: "release"
  BuildPlatform: "any cpu"

stages:
  - stage:
    displayName: Build
    jobs:
      - job:
        displayName: Build_And_Publish
        steps:
          - task: NuGetCommand@2
            displayName: Nuget_Restore
            inputs:
              command: 'restore'
              restoreSolution: '**/*.sln'
              feedsToUse: 'select'
          - task: VSBuild@1
            displayName: Build_Solution
            inputs:
              solution: '**\*.sln'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
              platform: '$(BuildPlatform)'
              configuration: '$(BuildConfiguration)'
          - task: PublishBuildArtifacts@1
            displayName: Publish_Artifact
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: 
    displayName: Infrastructure-Provisioning
    jobs:
      - job:
        displayName: Terraform
        steps:
           - task: TerraformInstaller@0
             inputs:
               terraformVersion: 'latest'
           - task: TerraformTaskV3@3
             displayName: init1
             inputs:
               provider: 'azurerm'
               command: 'init'
               commandOptions: '-input=false -backend=false'
              
           - task: TerraformTaskV3@3
             displayName: plan1
             inputs:
               provider: 'azurerm'
               command: 'plan'
               environmentServiceNameAzureRM: 'Pay-As-You-Go(eca7462f-847f-4132-a878-110a6e0bb87a)'
           - task: TerraformTaskV3@3
             displayName: apply1
             inputs:
               provider: 'azurerm'
               command: 'apply'
               environmentServiceNameAzureRM: 'Pay-As-You-Go(eca7462f-847f-4132-a878-110a6e0bb87a)'
